name: check

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: check-${{ github.head_ref }}
  cancel-in-progress: true

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install JS dependencies
        run: |
          npm ci

      - name: Install dependencies
        run: npm install

      - name: prettier check
        run: npx prettier -c .

      - name: astro check
        run: npx astro -c .
