name: check

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: check-${{ github.head_ref }}
  cancel-in-progress: true

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install JS dependencies
        run: |
          bun ci

      - name: Install dependencies
        run: bun install

      - name: prettier check
        run: bunx prettier -c .

      - name: astro check
        run: bunx astro -c .
