name: deploy-cloudflare

on:
  workflow_call:
    secrets:
      CLOUDFLARE_ZONE:
        required: true
      CLOUDFLARE_TOKEN:
        required: true

jobs:
  clear-cache:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod')

    permissions:
      contents: read
      id-token: write
      pull-requests: write
      checks: write

    runs-on: ubuntu-latest

    steps:
      - name: Purge Cloudflare Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
